CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    especie VARCHAR(255) NOT NULL,
    raca VARCHAR(255),
    idade INTEGER
);

CREATE TABLE eventos_preventivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_evento VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    data_realizacao DATE,
    data_proximo_vencimento DATE,
    pet_id BIGINT NOT NULL,
    CONSTRAINT fk_pet FOREIGN KEY (pet_id) REFERENCES pets(id)
);

-- Inserts iniciais com nomes diferenciados
INSERT INTO pets (nome, especie, raca, idade) VALUES ('Zeus', 'Cachorro', 'Pastor Alemão', 4);
INSERT INTO pets (nome, especie, raca, idade) VALUES ('Pandora', 'Gato', 'Maine Coon', 2);

INSERT INTO eventos_preventivos (tipo_evento, descricao, data_realizacao, data_proximo_vencimento, pet_id) 
VALUES ('Avaliação Cardiológica', 'Check-up preventivo anual do coração', '2026-02-10', '2027-02-10', 1);

INSERT INTO eventos_preventivos (tipo_evento, descricao, data_realizacao, data_proximo_vencimento, pet_id) 
VALUES ('Limpeza de Tártaro', 'Profilaxia dentária preventiva', '2026-04-05', '2027-04-05', 2);